### ISSUE TITLE
Hook Hatch Mech

### ISSUE THREAD

**Issue by gkrueger12** [olentangyfrc/DeepSpace-2019#103]
KEEP IT SIMPLE STUPID. 80/20 hook to move hatches

**Comment by gkrueger12** [comment]
<img width="308" alt="hatch hook mech" src="https://user-images.githubusercontent.com/39972010/51041759-a2a57a00-1588-11e9-93bb-20ccd392be87.PNG">

**Comment by gkrueger12** [comment]
See George for details

**Comment by worthp** [comment]
@Connor2573 this is what i mentioned earlier
