### ISSUE TITLE
Hab platform height cheat sheet

### ISSUE THREAD

**Issue by Eiim** [olentangyfrc/DeepSpace-2019#105]
Create a "cheat sheet" of the Hab platform in isometric view with pointers indicating platform level heights to lower platforms/ground.

**Comment by RileyMcGaughey** [comment]
![hab cheat sheet](https://user-images.githubusercontent.com/46425564/51076101-34cd8100-1662-11e9-9303-9b4ef1c725e7.PNG)

**Comment by Eiim** [comment]
Large one is done, small ones tomorrow
