### ISSUE TITLE
RoboRio Quantity

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#116]
Do we have enough of these?

I believe we have 5 that are fully functional:
Football
Turbo Sled
Zippy (2018 comp bot)
Janky (mec sled)
Wonky (mec sled)

Lets discuss on Saturday.

**Comment by mikagika** [comment]
#6 coming back today for testing. I'd like to see it get mounted on robot for testing so we can see it perform under some load. It flashed fine and I was able to push code to it, but I don't know what I did different from @mrbbking that might have fixed it when I took it apart to inspect/clean it.
