### ISSUE TITLE
Painting apparatus?

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#118]
Can we paint the apparatus?  Or will this be bad for vision? 

I think this might be good for the team if we slap an OZone logo on it?  Maybe put the logo on the side so it doesn't interfere with vision, rather than pain the whole thing?

**Comment by mikagika** [comment]
Ideally, it would be painted same as competition, but if we look for retro tape the same way we did last year, it won't matter. But the way we need to look for the white stripe on the carpet will be different. Not sure how exactly that's going to work, if we're even going to use it in an autonomous fashion. The retro tape vision targets may very well be sufficient.
