### ISSUE TITLE
Work out robot identification

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#131]

**Comment by sethstobart** [comment]
could you elaborate?

**Comment by worthp** [comment]
the MAC Address was not available when being set in .bashrc. I figured it out thanks to @mikagika  that it should probably be in .bash_profile instead of .bashrc . i can explain the diff to you if you want. I have opened an issue to make the change #135 . and i have updated the wiki, https://github.com/olentangyfrc/DeepSpace-2019/wiki/Getting-MAC-Address-from-Roborio
