### ISSUE TITLE
Need to change the location of MAC Address setting on rio

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#135]
The script to set MAC Addess needs to be relocated to /home/lvuser/.bash_profile from /home/lvuser/.bashrc. This will correct the the problem we had with MAC_ADDRESS coming back null.

I have already done this on the Football
wiki is updated, https://github.com/olentangyfrc/DeepSpace-2019/wiki/Getting-MAC-Address-from-Roborio

**Comment by sethstobart** [comment]
So we need to regrab the MAC address for each rio (sans football) and relabel physically as well as on hardware?

**Comment by sethstobart** [comment]
@Connor2573 @NotSketchyBen. This is something I'd like the new members to be able to do. We have documentation on the process in the wiki but I'd like to see them do it themselves. It's an important part of the code base now and they're gonna have to learn eventually.
