### ISSUE TITLE
Intake Grabber Code

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#141]
Need code to turn on a motor.  Needs to be able to turn the motor forward and backwards.  Two different buttons on a joystick.  This will run through a talon.  
Please let @olentangyfrcowner know what other specs you need and feel free to assign to whatever coder needs this job.

**Comment by sethstobart** [comment]
One rotation with mag encoder and 9:1 ratio is 36864 pos units
