### ISSUE TITLE
Hatch Panel

### ISSUE THREAD

**Issue by gkrueger12** [olentangyfrc/DeepSpace-2019#157]
Attach drawing file for Hatch panel so that Schmidt or I can cut it out on CNC
Lily wrap cut panel in velcro

**Comment by morganhowe** [comment]
[Link to hatch panel](https://workbench.grabcad.com/workbench/projects/gciNjevErZwofuxBHUlkGywi8HOOv5VYjQ5k2HiWN7YvWX#/file/414649936)

**Comment by Eiim** [comment]
I believe that solves the issue as both George and Schmidt have access to that link.
