### ISSUE TITLE
Develop Vision code for the white line

### ISSUE THREAD

**Issue by benschwartz9** [olentangyfrc/DeepSpace-2019#165]
- [ ] Determine correct LED for lighting 
- [ ] Find the correct mask
- [ ] Determine the correct algorithm to return the horizontal distance needed to line up with the line
- [ ] Return the horizontal distance value to the roboRio

Also look into photo receptors

**Comment by worthp** [comment]
This capability will most likely not be Vision. There are sensors that can detect white stripe. ask @Connor2573  for info

**Comment by mikagika** [comment]
The new PixyCam2s do a nice job of line detection too. Whether it's useful or not depends on what we want to do with the line.
