### ISSUE TITLE
Fix "broken template" issues

### ISSUE THREAD

**Issue by Eiim** [olentangyfrc/DeepSpace-2019#175]
Very frequently, SW2018 gives warning about broken/missing templates when opening files. Try to find a fix for this.

**Comment by DylanMires** [comment]
I did some research and I believe that when you add parts from andymark or other websites, the initial templates they use are different than the default ones we use. When we put it in our assembly, it may consider the parts as un supported

**Comment by morganhowe** [comment]
Go to tools > Options > Default Templates > Click the "..." next to the text box > Select the one template available.

**Comment by Eiim** [comment]
Closing, we'll direct people here if they continue to have this issue.
