### ISSUE TITLE
Fix lightweight/CAM issues

### ISSUE THREAD

**Issue by Eiim** [olentangyfrc/DeepSpace-2019#176]
SW keeps complaining about not being able to save nonexistent SW CAM data with lightweight components. Additionally, it keeps reverting components to lightweight. Investigate what this means, what causes this, and how we can fix it.

**Comment by olentangyfrcowner** [comment]
Any progress on this?

**Comment by Eiim** [comment]
Riley is looking into some possibilities

**Comment by morganhowe** [comment]
Settings > Assemblies > Un-check "Use Large Assembly Mode to improve performance..."
