### ISSUE TITLE
Required Reading for Software

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#18]
Please do a quick read. It will not be tested. Does this provide any insight to organizing our subsystems?

https://en.wikipedia.org/wiki/Guidance_system

**Comment by sethstobart** [comment]
http://sce.uhcl.edu/helm/rationalunifiedprocess/process/modguide/md_dsub.htm

This article is a bit more specific to the subsystem based workflow. The guidance introduction does a good job and this article may be too nitty gritty just throwing it out there.

**Comment by worthp** [comment]
@sethstobart  This is the stuff that gets into true software engineering. Of anyone is interested, I can speak to the concepts in that article.
