### ISSUE TITLE
Do we need a drafting project board?

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/DeepSpace-2019#183]
All drafting issues are ending up in general. Would we be better suited with a drafting board for these issues?

**Comment by Eiim** [comment]
My general feeling is yes, would like more input,

**Comment by olentangyfrcowner** [comment]
Yes.  Make it please @sethstobart

**Comment by Eiim** [comment]
Needs automation

**Comment by Eiim** [comment]
All good, I figured out how to do it.
