### ISSUE TITLE
Fix Chaney's printer

### ISSUE THREAD

**Issue by Eiim** [olentangyfrc/DeepSpace-2019#200]
Chaney's printer is having a lot of issues printing. This needs fixed.

**Comment by olentangyfrcowner** [comment]
Please refrain from making issues with this language.  
Can we make a check list of the specific issues?

**Comment by Eiim** [comment]
It hasn't been able to get past the first few layers in any of its last prints. It's unclear why this is.

**Comment by Eiim** [comment]
Morgan adjusted temps and it seems good
