### ISSUE TITLE
Wire an LED ring to Zippy - see Ben Schwartz for details

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#206]

**Comment by olentangyfrcowner** [comment]
@LillianMcGee we need more LED rings soldered to wire leads.  I'd say each one could get an 18" wire for it.

**Comment by mrbbking** [comment]
All LED rings we could find are wired up with bare leads. Adding ferrules now would make it harder to use them for testing, so ... we didn't do that.

Also added 3/8" heat shrink near the board to indicate LED color (green or white)

UNRESOLVED: strain relief for these leads. Please be gentle for now.

Well. Always be gentle with these, actually...
