### ISSUE TITLE
Make Models of Electrical Components

### ISSUE THREAD

**Issue by mrbbking** [olentangyfrc/DeepSpace-2019#212]
I'd like to have a set of electrical part models so we can experiment to find the best arrangement for them on the bots. They should be big enough to work with, but small enough to store neatly.

Overall outside dimensions of each piece are the only important part. We don't need surface features or accurately-rounded corners, so 3D printed with low detail or cut accurately from sheet goods would both work. The height dimension is not critical for this use.

Each part should have its name printed or written neatly on it.

Parts needed:

* RIO
* Power Distribution Panel
* Voltage Regulator Module
* Pneumatics Control Module
* Talons (8 of these)
* Main breaker
* Battery
* Air Compressor (footprint only)
* Air tank (footpring only)

**Comment by mrbbking** [comment]
Assigning to @sethstobart and @olentangyfrcowner for help in prioritizing and assigning.

**Comment by Eiim** [comment]
Putting under Drafting, although it  depends on how this ends up happening.

**Comment by Eiim** [comment]
Note: I think 1/4" is sufficient and will save time and filament

**Comment by mrbbking** [comment]
In the set I picked up today, I have

* RIO
* Compressor
* Batter
* PCM
* Talons

I know you were printing another piece today, but I don't remember which one.

Here's what's still missing:

* Power Distribution Panel
* Main Breaker
* Voltage Regulator Module
* Air Tank

**Comment by Eiim** [comment]
All models are done and given to Mr. King
