### ISSUE TITLE
Investigate GitKraken

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#22]
Take a look at https://www.gitkraken.com/git-client
it has tight integration with GitHub and is pretty easy to use for basic operations. We can discuss last week to see if we want to expose to the rest of the team.

I was exposed to this at work (it's what we use) and i think it helps. Other integrated git clients still work and of course github web ui works as well. I like the graphical visual and quick navigation of code tree

**Comment by mikagika** [comment]
Best name ever, no doubt, but after poking at it a bit, I think I still prefer Sourcetree.  [https://www.atlassian.com/software/sourcetree](https://www.atlassian.com/software/sourcetree) Mostly because it's easier to view the changes. At least from what I've been able to figure out.
