### ISSUE TITLE
Figure out how to get MAC address of network card on linux

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#24]

**Comment by mikagika** [comment]
ifconfig -a, ether field, at least on centos.

**Comment by worthp** [comment]
these were meant for those less informed ;-). i have an idea on how to support multiple bots on one code base.
@Connor2573 @NotSketchyBen  @ethandavis239 you guys are not off the hook.

**Comment by worthp** [comment]
this should work across various distros
ip link show dev enp0s31f6|tail -n 1|awk '{print $2}'
