### ISSUE TITLE
Shuffleboard Required Reading

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#25]
Take a look at this in it's entirety, https://wpilib.screenstepslive.com/s/currentCS/m/shuffleboard/c/230214 and this, https://github.com/wpilibsuite/shuffleboard/wiki/End-to-end-custom-data---widget-example . It will help us get our data organized and has a recording feature. There is a good chance it could be our logging solution.

**Comment by topfuel388** [comment]
Shuffle Board reading done!  This is a great tool.
