### ISSUE TITLE
REV magnetic limit switch 

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#283]
We need to create a part file for the following sensor.

http://www.revrobotics.com/rev-31-1462/

Please put it in the Common parts.  Don't put the step file.  Open it, and save it as Magnetic Limit Switch

**Comment by morganhowe** [comment]
In Ozone Common Parts under Magnetic Limit Switch.
Part files for both the magnet & switch.
