### ISSUE TITLE
GoPro Time Lapse

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#30]
Time Lapse set up from old gopro for Saturday meetings in the proving grounds, or the fab lab.  When the camera is set up and ready for time lapse, please see schmidt for tripod or a mounting location.

**Comment by gkrueger12** [comment]
Will drop off GoPro with a clear 64gb card tommorow (1/10/19)

**Comment by olentangyfrcowner** [comment]
I would really like this to be a high priority today, time lapse on the black gopro mounted up high in the shop.  See @olentangyfrcowner for location on mounting this camera

**Comment by priyankaagochiya** [comment]
Just as a written reference for everyone in case we ever forget how to record in time lapse: if you hold down the shutter (the record button) for three seconds, the camera will record in time lapse





On Saturday, January 12, 2019, 7:17 AM, olentangyfrcowner <notifications@github.com> wrote:


I would really like this to be a high priority today, time lapse on the black gopro mounted up high in the shop. See @olentangyfrcowner for location on mounting this camera
