### ISSUE TITLE
Open house flyer. The open house will be February 17th. We need to invite all current sponsors, potential sponsors, and district reps.

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/DeepSpace-2019#302]
This is very important! Need to make sure to spread the word about OZone!

**Comment by sethstobart** [comment]
![image-11](https://user-images.githubusercontent.com/25017045/52070968-013e9200-2550-11e9-9d5e-20eef3a464d0.jpg)

Example of a flyer from team Code Red

**Comment by kwelch0214** [comment]
https://docs.google.com/document/d/1PPVe_A0s3l0HkN84_qrxm-fi1qFMTy476kacBkWUoc0/edit?usp=sharing
