### ISSUE TITLE
OZone Logo with no back ground color

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#32]
Need a large format logo that when pasted matches the back ground of the particular slide show.  
![ozone logo 2018](https://user-images.githubusercontent.com/6354287/50724186-79cc4300-10b7-11e9-86dc-68e3c2dc2415.jpg)

**Comment by Eiim** [comment]
These are made, will put in Project X today if possible.

**Comment by Eiim** [comment]
In Project X, can be moved to done.
