### ISSUE TITLE
Leaderboard google sheet

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/DeepSpace-2019#328]
Create a google sheet that will keep track of slalom high scores.

**Comment by Eiim** [comment]
It's in the folder, with some test data in there. It doesn't handle ties in the top 4 very gracefully though.

**Comment by Eiim** [comment]
It's much more graceful about ties now, the person who got the score first gets the spot and subsequent tiers are knocked down in order. Unless you want more than 3 leaderboard spots, you can close this.
