### ISSUE TITLE
VIP Invite for season meetings

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#34]
Tweak our previous invite to match season dates and times.  Then see Mr. Chapman about creating mail merge to print the invites.  Logo needs to be black and white logo attached here.  Please use OZone brand
 fonts when typing, or see Schmidt for these fonts as they are new for 2019.  
![ethan_black_cycle](https://user-images.githubusercontent.com/6354287/50724226-0a0a8800-10b8-11e9-97c9-f98d6fdd0a09.png)

**Comment by mikagika** [comment]
Any movement on this?

**Comment by olentangyfrcowner** [comment]
Kim,
We need the invite finished on Saturday, so that you and Mr. Chapman can run the mail merge.  This need to be done on my teacher computer in lab 1412.  I have the excel file there with the names.

The invite should invite the VIP to any remaining building meetings Friday-Sunday for the remainder of the season.  Think principals, sponsors, etc.
