### ISSUE TITLE
Focused talk about what wpilib specific files should be included in .gitignore

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#39]
With the new gradle build process in wpi, there are a lot of files/dependencies that get brought in as a result of a build. We need to discuss which of these should/shouldn't be part of source control.

**Comment by schwartz3** [comment]
Added in the directories from WPILib(https://github.com/wpilibsuite/allwpilib/releases).  We can make additional change, but this prevents conflicts from the current repo and the WPILib directories.
