### ISSUE TITLE
Hab Platform Level Three (Tallest One)

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#42]
Find the dimensions and build one.

**Comment by olentangyfrcowner** [comment]
https://firstfrc.blob.core.windows.net/frc2019/DrawingPackages/TeamDrawings-Reduced.pdf

Plans should be on page one of link.

**Comment by Eiim** [comment]
Platform is 4 feet wide by 4 feet deep by 22 inches tall, confirmed by rule manual & CAD

**Comment by Eiim** [comment]
Height is from floor, not level 1 or 2

**Comment by olentangyfrcowner** [comment]
Printed drawings are in tube 4 of the development lab (code).
