### ISSUE TITLE
Hab Platform Level 2

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#43]
FInd the dimensions, create 2 of these platforms.

**Comment by olentangyfrcowner** [comment]
https://firstfrc.blob.core.windows.net/frc2019/DrawingPackages/TeamDrawings-Reduced.pdf

Drawing prints are also in tube 3 in the development lab.

**Comment by sethstobart** [comment]
One out of two done
