### ISSUE TITLE
Sourcing HDPE Sheets

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#46]
Please contact Peidmont plastics today (we need HDPE textured sheets).  Find out the cost of 48"x 96" sheet.  Or see if they can send you information on their product catalog for textured HDPE

**Comment by sethstobart** [comment]
Contacted Piedmont. Received estimate. The decision on how many and if we want to cheap out on 1/4 or splurge on the full 1/2.

**Comment by Eiim** [comment]
AndyMark tweeted that they may add textured HDPE. Who knows if the prices would be better, if it would be in sooner, etc. but something to keep an eye out for. If we have a decision to buy from Piedmont before AM releases it, though, I would just get it from them so we have it sooner.
