### ISSUE TITLE
Label KoP items with the date and names

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#47]
Seth, get it done.  But, please find someone (junior) who will do it with you, so they can do it next year for me.  

RoboRIO, radios, PD boards need names and dates.

Talons do not, just the date

Don't forget the new battery.  It's the black one on the charging station.

**Comment by sethstobart** [comment]
KoP is almost completely put away. Few things I don't know where we want to put or what they even are tbh.
