### ISSUE TITLE
Game piece part files to common parts folder

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#57]
Can we add the cargo and hatch panel SolidWorks part files to the common parts folder.

**Comment by Eiim** [comment]
Common Parts is supposed to be for perennial parts only. We'll put this in a separate 2019 project, which will also be designated a common parts project and include the field and any other such things.

**Comment by Eiim** [comment]
The 2019 Field project is now a Common Parts project. Not sure if the game pieces are in there or not.

**Comment by Eiim** [comment]
Never got closed
