### ISSUE TITLE
baseline code base

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#6]

**Comment by NotSketchyBen** [comment]
Similar talking point on this for Sunday, I believe there should be a commenting standard for methods, variables, etc. so everyone can understand the purpose of why something is there without having to ask someone

**Comment by worthp** [comment]
Yep. I want to put some standards docs on the project wiki, https://github.com/olentangyfrc/DeepSpace-2019/wiki . i know people have opinions on where we should put stuff, but we are putting it here cuz i'm tired of people just talking about why we don't do stuff

**Comment by worthp** [comment]
code is baselined in new repo.
