### ISSUE TITLE
Scoring Cheat sheets

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#60]
Use the link
https://www.chiefdelphi.com/t/cheat-sheet-deep-space-2019/337024

Get 18" x 24" prints (in color) of this and mount them to chip board using spray adhesive. 

Total QTY 3 needed
(Lillian and Olivia) Please see Ethan for help getting a color print from the printer in room 1412, See Seth on getting spray adhesive and chipboard.

**Comment by sethstobart** [comment]
![cheetsheet](https://user-images.githubusercontent.com/25017045/50859084-5677f100-1360-11e9-9513-d68aec9f3d40.png)
