### ISSUE TITLE
Rocket Height Cheat Sheet Creation

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#61]
Create a visual graphic with center points of hatch openings and height markings of top and bottom of all three hatch openings on the rocket.  This cheat can then be used by fabrication when designing mechanisms.  Please see Mr. Schmidt for approval.

**Comment by Eiim** [comment]
@olentangyfrcowner, do you want this on boards like #60?

**Comment by Eiim** [comment]
Large one is done, small ones tomorrow

**Comment by Eiim** [comment]
Files sent to the Arts department for printing, both this and #105
