### ISSUE TITLE
Mec sled dimension check

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#62]
Lauren, please measure all three mec sleds and find dimensions.  Comp bot from last year, and two remaining mec sleds.  Please write it down an let us know, by commenting on Git

**Comment by sethstobart** [comment]
Comp: 27.5 x 32.25

**Comment by sethstobart** [comment]
Vision Sled: 2705 x 32.25

**Comment by gkrueger12** [comment]
Janky: 27 x 32.25
