### ISSUE TITLE
Wire up the Nuclear Football (briefcase) with functional pneumatic controls.

### ISSUE THREAD

**Issue by sethstobart** [olentangyfrc/DeepSpace-2019#63]
The football needs to be wired up and made fully functional for new programmers to play with.

**Comment by Eiim** [comment]
Should the new brushless motors be added?

**Comment by worthp** [comment]
No. We want this for teaching new coders

**Comment by mrbbking** [comment]
Need to define "fully functional" - should be a discussion at next meeting.
