### ISSUE TITLE
Mec Sled Janky Needs

### ISSUE THREAD

**Issue by gkrueger12** [olentangyfrc/DeepSpace-2019#76]
- [x]   1. Need two Talons
- [x]   2. Need solenoid
- [x]   3. Need PCM
- [x]   4. Need compressor

Jacob you're going to be lead on this. Make sure everyone understands how the devices are wired. You can come to Seth or Mr. King with any questions.

**Comment by markbraniger** [comment]
Is there a layout drawing for this?
