### ISSUE TITLE
Change Gearing in Mec Sled Wonky

### ISSUE THREAD

**Issue by gkrueger12** [olentangyfrc/DeepSpace-2019#77]
@JacobBraniger , which of the gear boxes did you change?

**Comment by topfuel388** [comment]
I found 2 sets of gears 19t and 45t on sunday  They are in the cage in a  labeled white box.  Schmidt ordered 2 more sets.

**Comment by topfuel388** [comment]
Make sure you label the gearboxes with the ratio when ur done

**Comment by olentangyfrcowner** [comment]
@EricPohlman4611 @avamax03 Please see @topfuel388 (Mr. Miller) to show you how to do one, then you can do the other three.  

Be ready to get your fingers greasy!

When finished, please let @olentangyfrcowner know so we can push code and drive.

**Comment by olentangyfrcowner** [comment]
find @markbraniger to help you if Mr. Miller is busy

**Comment by topfuel388** [comment]
Use gloves.
