### ISSUE TITLE
Build andymark single stage elevator

### ISSUE THREAD

**Issue by gkrueger12** [olentangyfrc/DeepSpace-2019#78]

**Comment by olentangyfrcowner** [comment]
Link to assembly directons: (printed copy in tube 5 in code room)

https://andymark-weblinc.netdna-ssl.com/media/W1siZiIsIjIwMTkvMDEvMDMvMTkvMzgvMDEvZmIxYmQ3ZjMtNjhhOS00ODU0LTg0ZDMtMjlhZTYzMjQ3ODFkL2FtLTM4NDRhIDJ4MSBIRCBFbGV2YXRvciBBc3NlbWJseSBHdWlkZS5wZGYiXV0/am-3844a%202x1%20HD%20Elevator%20Assembly%20Guide.pdf?sha=bc97502a6dff913b
