### ISSUE TITLE
Decision on tag usage.

### ISSUE THREAD

**Issue by worthp** [olentangyfrc/DeepSpace-2019#85]
Github has a feature by which we can 'tag' the code base with a logical name and gives us the ability to easily retrieve any tagged code base whenever we want. We all need to be aware of when and under what criteria we want to tag the code in a conscious/strategic way. I know the team used tags last year and i think it was helpful. It would be good if all the leads an mentors around coding develop, agree and understand what that process is and how we can leverage

**Comment by mrbbking** [comment]
I suggest a small set of tags, with each branch/checkin/PR including two or three, such as:

1. Feature being added/modified/deleted
2. Which RIO it's meant for (following the branch-by-MAC-address idea)

**Comment by mikagika** [comment]
Tag by subsystem(s) affected?
