### ISSUE TITLE
Mec Chassis with open end plate into GrabCAD

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#90]
We need a mec chassis with only frame material, wheels, gearbox housing and cim motors.  Needs to have one end plate cut out in the middle from interior side rail to interior side rail.  See Mr. Miller or Schmidt for questions.

**Comment by topfuel388** [comment]
Make sure to use the dimensions of the existing mech chassis.  

For cutout at front, make end plates 6" on each side.  I think that is minimum per the rules.  I think that will create a 15.5" opening on the chassis,  Intake arms will eat up another 2in  leaving approx 13.5" opening.

**Comment by Eiim** [comment]
The minimum for a bumper-covered gap is 8". Not sure what the requirements
here are.

**Comment by topfuel388** [comment]
Does this sketch help?

**Comment by Eiim** [comment]
Not when there isn't a sketch attached

**Comment by topfuel388** [comment]
It's a hand sketch not a cad sketch

**Comment by Eiim** [comment]
Did you intend to attach a picture of it?

**Comment by topfuel388** [comment]
I attached it to the email both times.

I will try to get it into git hub now..

**Comment by topfuel388** [comment]
![img_20190109_105332547](https://user-images.githubusercontent.com/38573886/50935372-d45bfb00-1439-11e9-9f61-d7ca7c855f48.jpg)


I did it!!!  Had to attach image on PC.  You will have to teach me how to do with phone.  I'm too old for this. 

Miller

**Comment by Eiim** [comment]
Per R24, we just need 6 inches from each corner for bumpers, so given a 27.5" bot (see #62), we can have up to a 15.5" opening in the front. That is true to the description you gave in your original comment as well.

**Comment by topfuel388** [comment]
Great.  Good job..

**Comment by Eiim** [comment]
Got the base (unmodified) chassis, gonna need someone smarter to tell me if there's a difference between front and back though.

**Comment by topfuel388** [comment]
Front of chassis is the end with the cutout.

Miller

**Comment by topfuel388** [comment]
I looked at the chassis you drew.  I verified the 27 x 32.25 dim.  Looks very good!!

**Comment by Eiim** [comment]
Finally, this is done
