### ISSUE TITLE
775 Pro Motor Electrical connections

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#92]
We bought and received 775 motor connections from The Robot Space.

Need to understand how the are used and hooked up to 775 pro motors.

Mr. King you are lead on this, Sam K. and Sam S. should work with you to understand and be able to do it in the future.  Seth can show you were things are located.  This can be worked on Saturday. 

Connector link: https://www.therobotspace.com/ProductDetails.asp?ProductCode=trs-775C

775 Pro motor link: https://www.therobotspace.com/ProductDetails.asp?ProductCode=vex-217-4347

**Comment by mrbbking** [comment]
We're clear on how these'll work, but did not attach any.
Will review w/ Sam K and Sam S on Sat, then close this issue.
