### ISSUE TITLE
REV Robotics Magnetic Switches

### ISSUE THREAD

**Issue by olentangyfrcowner** [olentangyfrc/DeepSpace-2019#95]
Please see Schmidt for the hardware.  We have 10 of them.  Not looking for you guys to code these, but you know who to assign them too for preliminary testing with the football.

http://www.revrobotics.com/content/docs/REV-31-1462-DS.pdf

**Comment by olentangyfrcowner** [comment]
Do we need a mock up mechanism for these or will "the football" work?

**Comment by mikagika** [comment]
For the purpose of playing with code, the football should be fine. Just move the magnets manually.
